### ISSUE TITLE
Documentation on compiling a static library

### ISSUE THREAD

**Issue by noway** [westerndigitalcorporation/sweet-b#3]
It seems like `add_library` only allows shared library version: https://github.com/westerndigitalcorporation/sweet-b/blob/master/CMakeLists.txt#L126

I haven't found anywhere in documentation on how to build a static version. Is it supported? If not, is there any documentation on why not?

Thanks a lot, great library!!

**Comment by bmastenbrook** [comment]
Thanks for asking for this! PR #6 makes it easier to build a static version of Sweet B by using standard CMake features. To compile a static version of the library, add `-DBUILD_SHARED_LIBS=0` when configuring the project with CMake. As an example, to build a static version:

```
mkdir cmake-build-static
cd cmake-build-static
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0
make
```

This will produce a static library named `libsweet_b.a`.

You can also append `-DSB_TEST=0` to skip building the test harness as well.
